formatter: markdown table

recursive:
  enabled: false
  path: modules

content: |-
  {{ .Header }}

  ## Resources
  {{ range .Module.Resources }}
  - {{ .GetMode }}.{{ .Spec }} ({{ .Position.Filename }}#{{ .Position.Line }})
  {{- end }}

  ## Examples

  ```hcl
  {{ include "example/main.tf" }}
  ```

  {{ .Providers }}

  {{ .Outputs }}

  {{ .Inputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
